#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-multipart-post
Version  : 2.0.0
Release  : 7
URL      : https://rubygems.org/downloads/multipart-post-2.0.0.gem
Source0  : https://rubygems.org/downloads/multipart-post-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
## multipart-post
* http://github.com/nicksieger/multipart-post
![build status](https://travis-ci.org/nicksieger/multipart-post.png)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n multipart-post-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-multipart-post.gemspec

%build
gem build rubygem-multipart-post.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
multipart-post-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/multipart-post-2.0.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/multipart-post-2.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/multipart_post.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/multipartable.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/net/http/post/multipart.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/parts.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/multipart-post.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/test/multibyte.txt
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/test/net/http/post/test_multipart.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/test/test_composite_io.rb
/usr/lib64/ruby/gems/2.3.0/gems/multipart-post-2.0.0/test/test_parts.rb
/usr/lib64/ruby/gems/2.3.0/specifications/multipart-post-2.0.0.gemspec
